// The Wandering Die — Destiny Dice: preset decision bank, organized by category
// Each scenario carries 5 phrasing variants per outcome (per language) so a repeat
// roll on the same decision doesn't always show the exact same sentence.
(function (global) {
  'use strict';

  var CATEGORIES = [
    { id: 'social', i18n: { en: 'Social', es: 'Social', da: 'Socialt' } },
    { id: 'leisure', i18n: { en: 'Leisure', es: 'Ocio', da: 'Fritid' } },
    { id: 'food', i18n: { en: 'Food', es: 'Comida', da: 'Mad' } },
    { id: 'risk', i18n: { en: 'Adventure', es: 'Aventura', da: 'Eventyr' } },
    { id: 'work', i18n: { en: 'Work', es: 'Trabajo', da: 'Arbejde' } },
    { id: 'wellbeing', i18n: { en: 'Wellbeing', es: 'Bienestar', da: 'Trivsel' } }
  ];

  var SCENARIOS = [
    // Social
    { category: 'social', dc: 10, i18n: {
      en: { label: "Not sure whether to go out tonight?",
        low: ['Stay home and watch a movie', 'Better to stay in tonight', 'Choose a quiet night in', 'Stay home, save it for another night', 'Settle in and watch something'],
        high: ['Go out and grab a drink with friends', 'Get out there, even briefly', 'Say yes and head out tonight', 'Put on real pants and go', "Go out, it'll do you good"] },
      es: { label: '¿No sabés si salir esta noche?',
        low: ['Quedate en casa mirando una película', 'Mejor te quedás adentro con una peli', 'Elegí quedarte tranquilo en casa', 'Te conviene quedarte en casa esta noche', 'Optá por quedarte adentro viendo algo'],
        high: ['Salí a tomar algo con amigos', 'Andá, salí un rato esta noche', 'Vestite y salí a despejarte', 'Aceptá la salida, te va a hacer bien', 'Salí, aunque sea una hora'] },
      da: { label: 'Ved du ikke, om du skal ud i aften?',
        low: ['Bliv hjemme og se en film', 'Bedst at blive hjemme i aften', 'Vælg en stille aften indenfor', 'Bliv hjemme, gem det til en anden aften', 'Slå dig ned og se noget'],
        high: ['Gå ud og få en drink med venner', 'Kom ud, om så kun kort', 'Sig ja og tag ud i aften', 'Tag tøj på og kom ud', 'Gå ud, det vil gøre dig godt'] } } },
    { category: 'social', dc: 13, i18n: {
      en: { label: "Invited to a party where you know no one?",
        low: ['Send a polite excuse and stay in', 'Decline gracefully and skip it', "Let them know you can't make it", 'Sit this one out, no guilt', 'Stay out of this one'],
        high: ['Go anyway and introduce yourself', 'Show up even if you know no one', 'Walk in and start a conversation', 'Go and make a new contact or two', 'Go without overthinking it'] },
      es: { label: '¿Te invitaron a una fiesta donde no conocés a nadie?',
        low: ['Mandá una excusa amable y quedate tranquilo', 'Declina con cortesía y quedate en casa', 'Avisá que no podés ir esta vez', 'Mejor te la perdés, sin culpa', 'Quedate afuera de ésta, no pasa nada'],
        high: ['Andá igual y presentate', 'Metete igual, aunque no conozcas a nadie', 'Aparecé y hacé nuevos contactos', 'Cruzá la puerta y arrancá una charla', 'Andá sin pensarlo demasiado'] },
      da: { label: 'Inviteret til en fest, hvor du ikke kender nogen?',
        low: ['Send en høflig undskyldning og bliv hjemme', 'Sig pænt nej tak', 'Meld afbud denne gang', 'Spring den her over, uden dårlig samvittighed', 'Bliv væk fra den her'],
        high: ['Tag alligevel af sted og præsentér dig selv', 'Mød op, selvom du ikke kender nogen', 'Gå ind og start en samtale', 'Tag af sted og få en ny bekendtskab', 'Tag af sted uden at tænke for meget'] } } },
    { category: 'social', dc: 12, i18n: {
      en: { label: 'Need to break the ice with someone new?',
        low: ["Ask a genuine question about their day", 'Start with something simple and real', 'Show real interest first', "Ask something you're actually curious about", 'Ease in with an honest question'],
        high: ['Crack a terrible joke and see what happens', 'Risk it with an awful pun', 'Break the ice with humor, flop or not', 'Go for the bad joke on purpose', 'Just make the joke, why not'] },
      es: { label: '¿Tenés que romper el hielo con alguien nuevo?',
        low: ['Preguntale algo genuino sobre su día', 'Empezá con una pregunta simple y real', 'Mostrá interés genuino primero', 'Preguntale algo que de verdad te interese', 'Arrancá suave, con una pregunta honesta'],
        high: ['Tirale un chiste malísimo y ver qué pasa', 'Arriesgate con un chiste horrible', 'Rompé el hielo con humor, aunque falle', 'Probá un chiste malo a propósito', 'Hacé la broma, total ya está'] },
      da: { label: 'Skal du bryde isen med en ny person?',
        low: ['Spørg ægte ind til deres dag', 'Start med noget simpelt og ægte', 'Vis oprigtig interesse først', 'Spørg om noget, du faktisk er nysgerrig på', 'Start blødt med et ærligt spørgsmål'],
        high: ['Fyr en forfærdelig vittighed af og se, hvad der sker', 'Vov den elendige vittighed', 'Bryd isen med humor, gå eller ej', 'Kør den dårlige joke med vilje', 'Bare sig vittigheden, hvorfor ikke'] } } },
    { category: 'social', dc: 14, i18n: {
      en: { label: "Can't decide whether to send that message?",
        low: ['Wait until tomorrow to send it', 'Let it sit and send it later', 'Hold off a bit before sending', 'Better to wait for the right moment', 'Save it for later'],
        high: ['Send it right now, no overthinking', "Send it now, don't think twice", 'Hit send before you talk yourself out of it', 'Just send it already', 'Press send now'] },
      es: { label: '¿No sabés si mandar ese mensaje?',
        low: ['Esperá hasta mañana para mandarlo', 'Dejalo reposar y mandalo después', 'Aguantá un rato antes de mandarlo', 'Mejor esperá al momento justo', 'Guardalo para más tarde'],
        high: ['Mandalo ya mismo, sin darle más vueltas', 'Enviálo ahora, no lo pienses más', 'Dale enviar antes de arrepentirte', 'Mandalo de una vez', 'Apretá enviar ya'] },
      da: { label: 'Kan du ikke beslutte, om du skal sende den besked?',
        low: ['Vent til i morgen med at sende den', 'Lad den ligge og send den senere', 'Hold igen lidt før du sender den', 'Bedst at vente på det rette øjeblik', 'Gem den til senere'],
        high: ['Send den lige nu, uden at tænke mere over det', 'Send den nu, tøv ikke', 'Tryk send, før du fortryder', 'Bare send den nu', 'Tryk send med det samme'] } } },

    // Leisure
    { category: 'leisure', dc: 10, i18n: {
      en: { label: "Don't know what to watch tonight?",
        low: ['Something that makes you think — a documentary or drama', 'Pick a documentary that challenges you', 'Go heavier, a real drama', 'Try a documentary this time', 'Go for something with more substance'],
        high: ['A light, easy comedy', 'Something fun, no deep thinking needed', 'Put on a comedy and unwind', 'Pick something light to laugh at', 'A quick, no-fuss comedy'] },
      es: { label: '¿No sabés qué ver esta noche?',
        low: ['Algo que te haga pensar, un documental o drama', 'Elegí un documental que te desafíe', 'Andá por algo más denso, un drama', 'Probá un documental esta vez', 'Metele algo con más sustancia'],
        high: ['Una comedia liviana y fácil', 'Algo divertido y sin pensar mucho', 'Ponete una comedia y relajate', 'Elegí algo liviano para reírte', 'Una comedia rápida y sin vueltas'] },
      da: { label: 'Ved ikke, hvad du skal se i aften?',
        low: ['Noget der får dig til at tænke — en dokumentar eller drama', 'Vælg en dokumentar der udfordrer dig', 'Gå tungere, et rigtigt drama', 'Prøv en dokumentar denne gang', 'Vælg noget med mere substans'],
        high: ['En let, nem komedie', 'Noget sjovt, uden at tænke for meget', 'Sæt en komedie på og slap af', 'Vælg noget let at grine ad', 'En hurtig komedie uden filter'] } } },
    { category: 'leisure', dc: 11, i18n: {
      en: { label: 'A free afternoon and no plans?',
        low: ['Stay in and read', 'Use the time to read quietly', 'Grab a book and stay in', 'Spend the afternoon with a good book', 'Stay home, pick up something to read'],
        high: ['Go for a walk with no destination', 'Take an aimless walk outside', 'Walk for a while, no fixed plan', 'Get moving, even without a destination', 'Take a stroll somewhere'] },
      es: { label: '¿Tenés una tarde libre sin planes?',
        low: ['Quedate leyendo en casa', 'Aprovechá para leer tranquilo', 'Elegí un libro y quedate adentro', 'Pasá la tarde con un buen libro', 'Quedate en casa, agarrá algo para leer'],
        high: ['Salí a caminar sin rumbo', 'Andá a dar una vuelta sin destino', 'Caminá un rato, sin plan fijo', 'Salí a moverte, aunque sea sin rumbo', 'Date una vuelta por ahí'] },
      da: { label: 'En fri eftermiddag uden planer?',
        low: ['Bliv hjemme og læs', 'Brug tiden på at læse i ro', 'Tag en bog og bliv hjemme', 'Brug eftermiddagen på en god bog', 'Bliv hjemme, find noget at læse'],
        high: ['Gå en tur uden mål', 'Tag en formålsløs gåtur udenfor', 'Gå lidt, uden en fast plan', 'Kom ud og bevæg dig, uden mål', 'Tag en tur et sted hen'] } } },
    { category: 'leisure', dc: 9, i18n: {
      en: { label: "Torn about starting that new show?",
        low: ['Save it for the weekend', 'Wait until you have more time', 'Hold off until the weekend', 'Better to start it later, unhurried', 'Save it for another time'],
        high: ['Start it tonight', 'Go on, start it now', 'Watch the first episode now', "Start it, tonight's the night", "Begin it now, don't wait"] },
      es: { label: '¿Dudás si arrancar esa serie nueva?',
        low: ['Dejala para el finde', 'Guardala para cuando tengas más tiempo', 'Esperá al fin de semana para arrancarla', 'Mejor la arrancás con más calma después', 'Dejala para otro momento'],
        high: ['Arrancala esta noche', 'Dale, empezala ya', 'Metele el primer capítulo ahora', 'Arrancala, totalmente hoy', 'Empezala ya, no esperes más'] },
      da: { label: 'I tvivl om at starte den nye serie?',
        low: ['Gem den til weekenden', 'Vent til du har mere tid', 'Hold igen til weekenden', 'Bedst at starte den senere, i ro', 'Gem den til en anden gang'],
        high: ['Start den i aften', 'Kom nu, start den', 'Se første afsnit nu', 'Start den, i aften er aftenen', 'Begynd den nu, vent ikke'] } } },
    { category: 'leisure', dc: 12, i18n: {
      en: { label: 'Weekend indecision?',
        low: ['Stay home and recharge, no plans', 'Use the weekend to rest at home', 'No plans, keep it quiet at home', 'Take the chance to do nothing', 'Stay in and actually rest'],
        high: ['Plan a short getaway', 'Organize a quick trip this weekend', 'Plan something outside, even nearby', 'Break the routine with a small trip', 'Plan an outing, even a small one'] },
      es: { label: '¿Indecisión de fin de semana?',
        low: ['Quedate en casa recargando pilas, sin planes', 'Tomate el finde para descansar en casa', 'Sin planes, quedate tranquilo en casa', 'Aprovechá para no hacer nada', 'Quedate adentro y descansá de verdad'],
        high: ['Planeá una escapada corta', 'Organizá una salida corta este finde', 'Armá un plan afuera, aunque sea cerca', 'Salí de la rutina con una escapada', 'Planeá algo afuera, aunque sea chico'] },
      da: { label: 'Weekend-usikkerhed?',
        low: ['Bliv hjemme og oplad, ingen planer', 'Brug weekenden på at hvile hjemme', 'Ingen planer, hold det roligt hjemme', 'Grib chancen for at lave ingenting', 'Bliv hjemme og hvil dig for alvor'],
        high: ['Planlæg en kort udflugt', 'Arranger en hurtig tur denne weekend', 'Planlæg noget udendørs, selv i nærheden', 'Bryd rutinen med en lille tur', 'Planlæg en udflugt, om så lille'] } } },

    // Food
    { category: 'food', dc: 10, i18n: {
      en: { label: "Can't decide what to eat today?",
        low: ['Cook something with what you already have', 'Put something simple together from the pantry', 'Cook at home today', "Use what's in the fridge", 'Make something homemade'],
        high: ['Order in', 'Get delivery today', 'Let someone else cook today', 'Order something good, no cooking', 'Order food this time'] },
      es: { label: '¿No sabés qué comer hoy?',
        low: ['Cociná algo con lo que ya tenés en casa', 'Armá algo simple con lo que hay', 'Cociná en casa hoy', 'Usá lo que tenés en la heladera', 'Preparate algo casero'],
        high: ['Pedí algo de comida', 'Pedí delivery hoy', 'Dejá que cocinen por vos hoy', 'Pedí algo rico, sin cocinar', 'Encargá comida esta vez'] },
      da: { label: 'Kan du ikke beslutte, hvad du skal spise i dag?',
        low: ['Lav mad med det, du allerede har', 'Sæt noget simpelt sammen fra skabet', 'Lav mad hjemme i dag', 'Brug det, der er i køleskabet', 'Lav noget hjemmelavet'],
        high: ['Bestil noget mad', 'Få leveret mad i dag', 'Lad andre lave maden i dag', 'Bestil noget godt, uden madlavning', 'Bestil mad denne gang'] } } },
    { category: 'food', dc: 13, i18n: {
      en: { label: 'Craving something but hesitating?',
        low: ['Wait until tomorrow', 'Save it for another day', 'Hold off on it for today', 'Better to wait a little longer', 'Push it to tomorrow'],
        high: ['Treat yourself, you earned it', 'Go on, treat yourself', 'Allow yourself the craving today', 'Have it, no harm done', 'Indulge, guilt-free'] },
      es: { label: '¿Tenés antojo pero dudás?',
        low: ['Esperá hasta mañana', 'Dejalo para otro día', 'Aguantá el antojo por hoy', 'Mejor esperá un poco más', 'Postergalo hasta mañana'],
        high: ['Date el gusto, te lo ganaste', 'Dale, date el gusto', 'Permitite el capricho hoy', 'Comételo, no pasa nada', 'Date el gusto sin culpa'] },
      da: { label: 'Har du lyst til noget, men tøver?',
        low: ['Vent til i morgen', 'Gem det til en anden dag', 'Hold igen med det i dag', 'Bedst at vente lidt længere', 'Udskyd det til i morgen'],
        high: ['Forkæl dig selv, du har fortjent det', 'Kom nu, forkæl dig selv', 'Tillad dig selv trangen i dag', 'Tag den, ingen skade sket', 'Nyd det, uden dårlig samvittighed'] } } },
    { category: 'food', dc: 11, i18n: {
      en: { label: 'New restaurant or the usual spot?',
        low: ["The usual spot, you know it works", "Go to the usual place, it's safe", "Don't risk it, stick with the reliable one", 'Stay with the one you already know', 'The usual never fails'],
        high: ['Try the new place', 'Give the new restaurant a shot', 'Give the new spot a chance', 'Try something different today', 'Take the risk on the new one'] },
      es: { label: '¿Restaurante nuevo o el de siempre?',
        low: ['El de siempre, sabés que funciona', 'Andá al de siempre, seguro', 'No arriesgues, el de confianza', 'Quedate con el que ya conocés', 'El de siempre no falla'],
        high: ['Probá el lugar nuevo', 'Animate al restaurante nuevo', 'Dale una chance al lugar nuevo', 'Probá algo distinto hoy', 'Arriesgá con el nuevo'] },
      da: { label: 'Ny restaurant eller det sædvanlige sted?',
        low: ['Det sædvanlige sted, du ved det virker', 'Tag til det sædvanlige sted, det er sikkert', 'Tag ingen chancer, hold dig til det pålidelige', 'Bliv ved det, du allerede kender', 'Det sædvanlige svigter aldrig'],
        high: ['Prøv det nye sted', 'Giv den nye restaurant en chance', 'Giv det nye sted en chance', 'Prøv noget andet i dag', 'Tag chancen med det nye'] } } },
    { category: 'food', dc: 8, i18n: {
      en: { label: 'Debating a second helping?',
        low: ['Leave it there', "Stop there, that's enough", 'Skip seconds this time', 'Stick with what you had', "Leave it as is, that's plenty"],
        high: ['Go for seconds', 'Go on, have another helping', 'Serve a bit more', "Have seconds, it's worth it", 'Go get more'] },
      es: { label: '¿Dudás si repetir el plato?',
        low: ['Dejalo ahí nomás', 'Frená ahí, ya está bien', 'No repitas esta vez', 'Quedate con lo que comiste', 'Dejalo así, alcanza'],
        high: ['Repetí sin culpa', 'Dale, repetí una vez más', 'Serví un poco más', 'Repetí, total vale la pena', 'Andá por más'] },
      da: { label: 'Overvejer du en portion mere?',
        low: ['Lad det være', 'Stop der, det er nok', 'Spring en portion mere over denne gang', 'Bliv ved det, du fik', 'Lad det være som det er, det er rigeligt'],
        high: ['Tag en portion mere', 'Kom nu, tag en omgang til', 'Server lidt mere', 'Tag en portion mere, det er det værd', 'Gå efter mere'] } } },

    // Adventure / risk
    { category: 'risk', dc: 15, i18n: {
      en: { label: "Someone's offering you something you've never tried?",
        low: ['Save it for another time', 'Wait for a better moment', 'Push it off, not today', 'Save it for later', 'Better to let it pass for now'],
        high: ['Go for it', 'Go on, take the leap', 'This is your moment, do it', 'Take the risk and try it', 'Jump in and try it'] },
      es: { label: '¿Te ofrecen probar algo que nunca hiciste?',
        low: ['Dejalo para otra ocasión', 'Esperá un mejor momento', 'Postergalo, no es hoy', 'Guardalo para más adelante', 'Mejor lo dejás pasar por ahora'],
        high: ['Animate y probalo', 'Dale, lanzate a probarlo', 'Es tu momento, hacelo', 'Arriesgate y probalo', 'Tirate a la pileta, probalo'] },
      da: { label: 'Nogen tilbyder dig noget, du aldrig har prøvet?',
        low: ['Gem det til en anden gang', 'Vent på et bedre tidspunkt', 'Udskyd det, ikke i dag', 'Gem det til senere', 'Bedst at lade det ligge for nu'],
        high: ['Kast dig ud i det', 'Kom nu, tag springet', 'Det er dit øjeblik, gør det', 'Tag chancen og prøv det', 'Hop ud i det og prøv'] } } },
    { category: 'risk', dc: 10, i18n: {
      en: { label: 'The long scenic road or the short one?',
        low: ["The short one, you're already running late", 'Take the short one, no time to spare', 'Better to go quick today', 'Take the short route', 'The short one suits you now'],
        high: ['The long one, the view is worth it', 'Take the long way, enjoy it', 'Take your time, go the scenic route', 'The long road makes sense today', 'Choose the view, go slow'] },
      es: { label: '¿El camino largo y lindo o el corto?',
        low: ['El corto, ya se te hizo tarde', 'Andá por el corto, no hay tiempo', 'Mejor el rápido hoy', 'Tomá el camino corto', 'El corto te conviene ahora'],
        high: ['El largo, el paisaje vale la pena', 'Andá por el largo, disfrutalo', 'Tomate el tiempo, andá por el lindo', 'El camino largo hoy tiene sentido', 'Elegí el paisaje, andá despacio'] },
      da: { label: 'Den lange smukke vej eller den korte?',
        low: ['Den korte, du er allerede sent på den', 'Tag den korte, der er ikke tid', 'Bedst at skynde sig i dag', 'Tag den korte rute', 'Den korte passer dig bedst nu'],
        high: ['Den lange, udsigten er det værd', 'Tag den lange vej, nyd den', 'Tag dig tid, tag den smukke rute', 'Den lange vej giver mening i dag', 'Vælg udsigten, gå langsomt'] } } },
    { category: 'risk', dc: 16, i18n: {
      en: { label: 'A spontaneous trip lands in your lap?',
        low: ['Stay and plan it properly for later', 'Wait and organize it calmly', 'Better to plan it another time', "Save it for when it's more sorted", 'Stay this time, plan it out later'],
        high: ['Hop on, no second-guessing', 'Go on, hop on now', 'Say yes to the trip, no doubts', 'Get on board right now', 'Say yes and hop on'] },
      es: { label: '¿Te proponen un viaje improvisado?',
        low: ['Quedate y planealo mejor para después', 'Esperá y organizalo con calma', 'Mejor lo planeás para otro momento', 'Dejalo para cuando esté más armado', 'Quedate esta vez, organizalo después'],
        high: ['Subite sin pensarlo dos veces', 'Andá, subite ya', 'Aceptá el viaje, sin dudar', 'Subite al viaje ahora mismo', 'Decí que sí y subite'] },
      da: { label: 'En spontan tur falder dig i skødet?',
        low: ['Bliv hjemme og planlæg den ordentligt senere', 'Vent og organiser det roligt', 'Bedst at planlægge det en anden gang', 'Gem det til når det er bedre planlagt', 'Bliv denne gang, planlæg det senere'],
        high: ['Hop på, uden at tænke to gange', 'Kom nu, hop på nu', 'Sig ja til turen, uden tvivl', 'Kom om bord lige nu', 'Sig ja og hop på'] } } },
    { category: 'risk', dc: 14, i18n: {
      en: { label: "Not sure whether to speak up in that meeting?",
        low: ['Wait for a better moment', 'Hold off and find a better chance', 'Let it pass for now', "Wait until it's your turn", 'Better to wait a bit longer'],
        high: ['Raise your hand and say it', 'Speak up now, say it', "Don't hold it back, say it", 'Take the floor now', 'Say it, this is your moment'] },
      es: { label: '¿No sabés si hablar en esa reunión?',
        low: ['Esperá tu momento', 'Aguantá y buscá mejor ocasión', 'Dejalo pasar por ahora', 'Esperá a que sea tu turno', 'Mejor esperá un poco más'],
        high: ['Levantá la mano y decilo', 'Hablá ahora, decilo', 'No te lo guardes, decilo', 'Tomá la palabra ya', 'Decilo, es tu momento'] },
      da: { label: 'Usikker på, om du skal sige noget til det møde?',
        low: ['Vent på et bedre tidspunkt', 'Hold igen og find en bedre chance', 'Lad det ligge for nu', 'Vent til det er din tur', 'Bedst at vente lidt længere'],
        high: ['Ræk hånden op og sig det', 'Sig det nu, sig det', 'Hold det ikke tilbage, sig det', 'Tag ordet nu', 'Sig det, det er dit øjeblik'] } } },

    // Work
    { category: 'work', dc: 9, i18n: {
      en: { label: "Not sure where to start your day?",
        low: ['Start with something quick to build momentum', 'Start light, build momentum', 'Clear something small off the list first', 'Start with the easy stuff', 'Start simple to get into rhythm'],
        high: ['Tackle the hardest task first', 'Face the hard one first', 'Start with what weighs the most', 'Get the heavy thing done now', 'Go straight for the tough one'] },
      es: { label: '¿No sabés por dónde empezar el día?',
        low: ['Arrancá con algo rápido para agarrar impulso', 'Empezá liviano, tomá impulso', 'Sacate algo chico de encima primero', 'Arrancá con lo fácil', 'Empezá simple para entrar en ritmo'],
        high: ['Arrancá con la tarea más difícil', 'Enfrentá lo difícil primero', 'Empezá por lo que más pesa', 'Sacate lo pesado de encima ya', 'Andá directo a lo complicado'] },
      da: { label: 'Usikker på, hvor du skal starte din dag?',
        low: ['Start med noget hurtigt for at få gang i det', 'Start let, byg momentum', 'Ryd noget småt af vejen først', 'Start med det nemme', 'Start simpelt for at komme i gang'],
        high: ['Tag den sværeste opgave først', 'Tag den svære først', 'Start med det, der vejer mest', 'Få det tunge overstået nu', 'Gå direkte efter det komplicerede'] } } },
    { category: 'work', dc: 11, i18n: {
      en: { label: 'Hesitating on sending that email?',
        low: ['Read it over once more first', 'Reread it before sending', 'Give it one more pass', 'Double check it before sending', 'Better to review it first'],
        high: ['Send it now', "Send it now, it's ready", "Hit send, it's good", 'Send it already', 'Press send right now'] },
      es: { label: '¿Dudás si mandar ese mail ahora?',
        low: ['Revisalo una vez más antes', 'Releelo antes de mandarlo', 'Dale una repasada más', 'Chequealo de nuevo antes de enviar', 'Mejor revisalo primero'],
        high: ['Mandalo ya', 'Enviálo ahora', 'Dale enviar, ya está listo', 'Mandalo de una', 'Apretá enviar ahora mismo'] },
      da: { label: 'Tøver du med at sende den mail?',
        low: ['Læs den igennem én gang til først', 'Genlæs den før du sender', 'Giv den et gennemsyn til', 'Dobbelttjek den før afsendelse', 'Bedst at gennemgå den først'],
        high: ['Send den nu', 'Send den nu, den er klar', 'Tryk send, den er god', 'Send den allerede', 'Tryk send med det samme'] } } },
    { category: 'work', dc: 8, i18n: {
      en: { label: 'Wondering if it\'s break time?',
        low: ['Push on a little longer', 'Hold on a bit more', 'Push a little further before stopping', "Keep going, you're almost there", 'A bit more, then take a break'],
        high: ['Take 10 minutes for yourself', 'Take a break now', 'Stop for a bit, you need it', 'Step away for a while, then return', 'Give yourself a breather now'] },
      es: { label: '¿Dudás si tomarte un descanso?',
        low: ['Seguí un poco más', 'Aguantá un rato más', 'Empujá un poco más antes de parar', 'Seguí, ya casi terminás', 'Un poco más y después parás'],
        high: ['Tomate 10 minutos', 'Hacé una pausa ahora', 'Parate un rato, lo necesitás', 'Cortá un rato, después seguís', 'Date un respiro ya'] },
      da: { label: 'Overvejer du en pause?',
        low: ['Fortsæt lidt længere', 'Hold ud lidt mere', 'Skub lidt mere før du stopper', 'Fortsæt, du er næsten der', 'Lidt mere, så holder du pause'],
        high: ['Tag 10 minutter til dig selv', 'Tag en pause nu', 'Stop lidt, du trænger til det', 'Gå væk et stykke tid, kom så tilbage', 'Giv dig selv en pause nu'] } } },
    { category: 'work', dc: 15, i18n: {
      en: { label: 'A new project lands on your desk — take it?',
        low: ["Decline, it's not the right moment", 'Say no for now', 'Better to let this one pass', "Not your moment, decline it", 'Turn it down for now'],
        high: ["Take it, the challenge is worth it", 'Say yes, go for it', "Take it, it's a good opportunity", 'Accept the challenge', 'Say yes, take it'] },
      es: { label: '¿Te ofrecen un proyecto nuevo, lo aceptás?',
        low: ['Declinalo, no es el momento', 'Decí que no por ahora', 'Mejor lo dejás pasar esta vez', 'No es tu momento, declinalo', 'Rechazalo por ahora'],
        high: ['Aceptalo, el desafío vale la pena', 'Decí que sí, animate', 'Tomalo, es una buena oportunidad', 'Aceptá el reto', 'Dale que sí, aceptalo'] },
      da: { label: 'Et nyt projekt lander på dit skrivebord — tager du det?',
        low: ['Sig nej tak, det er ikke det rette tidspunkt', 'Sig nej for nu', 'Bedst at lade denne gå', 'Ikke dit øjeblik, sig nej', 'Afvis den for nu'],
        high: ['Tag det, udfordringen er det værd', 'Sig ja, gå efter det', 'Tag det, det er en god mulighed', 'Tag udfordringen op', 'Sig ja, tag den'] } } },

    // Wellbeing
    { category: 'wellbeing', dc: 12, i18n: {
      en: { label: "Not feeling like training today?",
        low: ['Rest, your body needs it', 'Skip it today, rest up', "Your body's asking for rest, listen to it", 'Skip today, rest easy', 'Better to rest this time'],
        high: ["Go anyway, even if it's short", 'Move a little anyway', 'Even a short workout counts, go', "Go, even if it's light", 'Do it anyway, even briefly'] },
      es: { label: '¿No tenés ganas de entrenar hoy?',
        low: ['Descansá, tu cuerpo lo necesita', 'Dejalo pasar hoy, descansá', 'Tu cuerpo pide descanso, hacele caso', 'Saltealo hoy, descansá tranquilo', 'Mejor descansá esta vez'],
        high: ['Andá igual, aunque sea corto', 'Movete un poco igual', 'Aunque sea poco, entrená', 'Andá, aunque sea flojo', 'Metele aunque sea corto'] },
      da: { label: 'Ikke i humør til at træne i dag?',
        low: ['Hvil dig, din krop har brug for det', 'Spring det over i dag, hvil dig', 'Din krop beder om hvile, lyt til den', 'Spring i dag over, hvil roligt', 'Bedst at hvile denne gang'],
        high: ['Gå alligevel, selv hvis det er kort', 'Bevæg dig lidt alligevel', 'Selv en kort træning tæller, gå', 'Gå, selv hvis det er let', 'Gør det alligevel, om så kort'] } } },
    { category: 'wellbeing', dc: 9, i18n: {
      en: { label: 'Torn on a nap?',
        low: ['Push through and stay awake', 'Stay awake a bit longer', "Hold on, don't nap now", 'Stay up a little more', 'Resist the nap this time'],
        high: ['Take the nap', 'Go on, nap', 'Lie down for a bit', 'Sleep a little, you need it', 'Take the chance and nap'] },
      es: { label: '¿Dudás si dormir una siesta?',
        low: ['Aguantá despierto/a', 'Seguí despierto/a un rato más', 'Aguantá, no te duermas ahora', 'Quedate despierto/a un poco más', 'Resistí la siesta esta vez'],
        high: ['Dormila', 'Date la siesta', 'Echate un rato', 'Dormí un poco, lo necesitás', 'Aprovechá y dormila'] },
      da: { label: 'I tvivl om en lur?',
        low: ['Kæmp videre og bliv vågen', 'Bliv vågen lidt længere', 'Hold ud, tag ikke en lur nu', 'Bliv oppe lidt mere', 'Modstå luren denne gang'],
        high: ['Tag luren', 'Kom nu, tag en lur', 'Læg dig lidt ned', 'Sov lidt, du trænger til det', 'Grib chancen og tag en lur'] } } },
    { category: 'wellbeing', dc: 13, i18n: {
      en: { label: "Thinking of calling someone you miss?",
        low: ['Send a message first', 'Text them before calling', 'Start with a message, not the call', 'Send something short first', 'Try a text first'],
        high: ['Call them right now', "Call now, don't wait", 'Call them, stop overthinking it', 'Make the call now', 'Call them already'] },
      es: { label: '¿Pensás en llamar a alguien que extrañás?',
        low: ['Escribile un mensaje primero', 'Mandale un mensaje antes', 'Empezá con un mensaje, no la llamada', 'Escribile algo corto primero', 'Probá con un mensaje antes'],
        high: ['Llamalo/a ahora mismo', 'Marcá ya, no esperes', 'Llamalo/a, no lo pienses más', 'Hacé la llamada ahora', 'Llamalo/a de una vez'] },
      da: { label: 'Tænker du på at ringe til nogen, du savner?',
        low: ['Send en besked først', 'Skriv til dem før du ringer', 'Start med en besked, ikke opkaldet', 'Send noget kort først', 'Prøv en besked først'],
        high: ['Ring til dem lige nu', 'Ring nu, vent ikke', 'Ring til dem, tænk ikke mere over det', 'Foretag opkaldet nu', 'Ring til dem allerede'] } } },
    { category: 'wellbeing', dc: 16, i18n: {
      en: { label: 'Craving change but hesitating?',
        low: ['Wait for the right moment', 'Hold off a bit longer before changing', 'Let it settle before deciding', "Wait until you're more sure", 'Better to wait a little'],
        high: ['Go for the change', 'Go on, make the change', "It's time for the change, go for it", 'Take the leap into change now', 'Go after the change'] },
      es: { label: '¿Tenés ganas de un cambio pero dudás?',
        low: ['Esperá el momento justo', 'Aguantá un poco más antes de cambiar', 'Dejalo madurar antes de decidir', 'Esperá a estar más seguro/a', 'Mejor esperá un poco'],
        high: ['Animate al cambio', 'Dale, hacé el cambio', 'Es hora del cambio, animate', 'Lanzate al cambio ahora', 'Andá por el cambio'] },
      da: { label: 'Trang til forandring, men tøver?',
        low: ['Vent på det rette tidspunkt', 'Hold igen lidt mere før du ændrer det', 'Lad det bundfælde sig før du beslutter', 'Vent til du er mere sikker', 'Bedst at vente lidt'],
        high: ['Kast dig ud i forandringen', 'Kom nu, lav forandringen', 'Det er tid til forandring, kast dig ud i det', 'Tag springet til forandring nu', 'Gå efter forandringen'] } } }
  ];

  global.WD_DICE_CATEGORIES = CATEGORIES;
  global.WD_DICE_SCENARIOS = SCENARIOS;
})(window);
